name: PacocaCraft
version: 0.1
description: Private plugin for server

main: com.jabyftw.pacocacraft.PacocaCraft
author: rfsantos1996
depend: [Vault]

# Leave this here for later
#commands:
#  flagrate:
#    description: Set yourself on fire.
#    aliases: [combust_me, combustMe]
#    permission: inferno.flagrate
#    usage: Syntax error! Simply type /&lt;command&gt; to ignite yourself.
#  burningdeaths:
#    description: List how many times you have died by fire.
#    aliases: [burning_deaths, burningDeaths]
#    permission: inferno.burningdeaths
#    usage: |
#      /&lt;command&gt; [player]
#      Example: /&lt;command&gt; - see how many times you have burned to death
#      Example: /&lt;command&gt; CaptainIce - see how many times CaptainIce has burned to death