name: PacocaCraft
version: 0.1
description: Private plugin for server

main: com.jabyftw.pacocacraft.PacocaCraft
author: rfsantos1996
depend: [Vault, ProtocolLib]

commands:
  login:
    aliases: [l, entrar]
  register:
    aliases: [registrar, reg]
  godmode:
    aliases: god
  gamemode:
    aliases: gm
  fly:
    aliases: flight
  teleport:
    aliases: tp
  teleporthere:
    aliases: tphere
  spawn:
    description: dont know if I can remove every command attribute
  spawnset:
    description: dont know if I can remove every command attribute
  world:
    aliases: world
  give:
    description: dont know if I can remove every command attribute
  itens:
    aliases: item
  back:
    aliases: [b, voltar]
  heal:
    aliases: curar
  enchant:
    aliases: [enchantment, encantar]
  clearenchantment:
    aliases: [desencantar, clearenchant, cenchant, cenchantment]
  workbench:
    description: dont know if I can remove every command attribute
  list:
    aliases: [players, jogadores, lista]
  whisper:
    aliases: [m, msg]
  r:
    description: dont know if I can remove every command attribute
  broadcast:
    description: dont know if I can remove every command attribute
  clear:
    aliases: [cl, clearinventory]
  suicide:
    description: dont know if I can remove every command attribute
  kill:
    aliases: [matar]
  killall:
    description: dont know if I can remove every command attribute
  spawnmob:
    aliases: spawnmobs
  mute:
    description: dont know if I can remove every command attribute
  ptime:
    aliases: tempo
  pweather:
    aliases: clima
  repair:
    aliases: [reparar, fix]
  spyinv:
    aliases: [invsee, inventory, inventario]
  speed:
    aliases: [flyspeed, walkspeed]
  exp:
    aliases: [experience]
  level:
    aliases: [leveis, levels, setlevel]
  feed:
    aliases: [eat, hunger]
  hat:
    aliases: [chapeu]
  top:
    description: dont know if I can remove every command attribute
  changeuser:
    aliases: [changeusername, mudarusuario, mudaruser, mudarnome]
  changepass:
    aliases: [changepassword, mudarsenha, passwordchange, passchange]